<?= $this->doctype() . "\n" ?>
<html>
<head>
<?= $this->headMeta()->setIndent('    ')
    ->prependHttpEquiv('Content-Style-Type', 'text/css'). "\n"; ?>
<?= $this->headTitle('Administration')
    ->setIndent('    ')->setSeparator(' / ') . "\n    "; ?>
<?= $this->headScript()->prependFile(
    'http://html5shiv.googlecode.com/svn/trunk/html5.js',
    'text/javascript',
    array('conditional'=>'IE')) . "\n"; ?>
<?= $this->headStyle()->setIndent('    ')
    ->prependStyle('article, aside, dialog, figure, footer, header, hgroup, nav, section {display: block;}') . "\n" ?>
<?= $this->headLink()->setIndent('    ')
    ->appendStylesheet($this->includeModifiedDate('/css/reset.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/960.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/text.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/style.css')) . "\n"; ?>
</head>
<body id="page">

        <header id="header" class="container_12" role="banner">
            <hgroup>
                <h1><a href="/admin">ZF Planet Administration</a></h1>
            </hgroup>
        </header>
        
        <div class="clear"></div>

        <div id="content-wrapper" class="container_12">
            <div id="content" class="grid_9" role="main">
                <?= $this->layout()->content ?>
            </div>
        </div>

        <div class="clear"></div>

        <footer id="footer" class="container_12" role="contentinfo">
            <p><a href="http://github.com/padraic/ZFPlanet">ZFPlanet</a> &copy; 2010 Pádraic Brady</p>
            <p>Powered by <a href="http://framework.zend.com">Zend Framework</a></p>
        </footer>

</body>
</html>
