<? if (count($this->paginator) == 0): ?>
    <p>No entries to display</p>
<? else: ?>
    <? $this->partial()->setObjectKey('entry') ?>
    <? foreach ($this->paginator as $entry): ?>
        <article class="hentry <?= $this->cycle(array('odd','even'))->next() ?>"
        id="<?= $this->escape($entry->id) ?>">
        <?= $this->partial('_partials/_entry.phtml', $entry) ?>
        </article>
    <? endforeach; ?>
    
    <?
    $paginator = $this->paginationControl($this->paginator, 'Sliding', '_partials/_paginator.phtml');
    $this->placeholder('paginator')->set($paginator);
    ?>
<? endif; ?>
