<header>
    <h2>Create/Renew Subscription</h2>
</header>
<div>
    <p>Submit the name of any Topic (Atom/RSS feed) URI, and a subscription
    will be attempted. The Pubsubhubbub Hub endpoints advertised by the
    feed will be used if available.</p>
    <? if (isset($this->messages)): ?>
        <? foreach ($this->messages as $message): ?>
            <p class="flashmessage"><?= $message ?></p>
        <? endforeach; ?>
    <? endif; ?>
    <form id="subscribe_form" action="/admin/subscribe/process" method="post">
        <input type="text" name="topic_uri" value="" /></br>
        <input type="submit" name="submit" value="Subscribe" />
    </form>
</div>
