<?= $this->doctype() . "\n" ?>
<html>
<head>
<?= $this->headMeta()->setIndent('    ')
    ->prependHttpEquiv('Content-Style-Type', 'text/css'). "\n"; ?>
<?= $this->headTitle('ZF Planet')
    ->setIndent('    ')->setSeparator(' / ') . "\n    "; ?>
<?= $this->headScript()->prependFile(
    'http://html5shiv.googlecode.com/svn/trunk/html5.js',
    'text/javascript',
    array('conditional'=>'IE')) . "\n"; ?>
<?= $this->headStyle()->setIndent('    ')
    ->prependStyle('article, aside, dialog, figure, footer, header, hgroup, nav, section {display: block;}') . "\n" ?>
<?= $this->headLink()->setIndent('    ')
    ->appendStylesheet($this->includeModifiedDate('/css/reset.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/960.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/text.css'))
    ->appendStylesheet($this->includeModifiedDate('/css/style.css')) . "\n"; ?>
    <link rel="alternate" type="application/atom+xml" href="http://zfplanet/feed/atom"/>
    <link rel="alternate" type="application/rss+xml" href="http://zfplanet/feed/rss"/>
    <link rel="profile" href="http://microformats.org/profile/hcard"/>
</head>
<body id="page">

        <header id="header" class="container_12" role="banner">
            <hgroup>
                <h1><a href="/">ZF Planet</a></h1>
            </hgroup>
        </header>
        
        <div class="clear"></div>

        <div id="content-wrapper" class="container_12">
            <div id="content" class="hfeed grid_9" role="main">
                <?php echo $this->layout()->content ?>
            </div>

            <div id="sideinfo" class="grid_3">

                <aside class="sideinfo">
                    <header>
                        <h3>Feeds</h3>
                    </header>
                    <a href="/feed/atom">Atom 1.0 <img src="/images/feedicon.gif" alt="Atom 1.0 Feed"/></a><br/>
                    <a href="/feed/rss">RSS 2.0 <img src="/images/feedicon.gif" alt="Atom 1.0 Feed"/></a><br/><br/>
                    <a href="/opml">OPML 2.0 Blogroll <img src="/images/feedicon.gif" alt="OPML 2.0 Subscription List"/>
                </aside>

                <aside class="sideinfo">
                    <header>
                        <h3>Bloggers</h3>
                    </header>
                    <?= $this->listBloggers() ?>
                </aside>

            </div>
            
        </div>
        
        <? if ($this->placeholder('paginator')): ?>
            <div class="clear"></div>
            <nav id="paginate" class="container_12" role="navigation">
                <?= $this->placeholder('paginator') ?>
            </nav>
        <? endif; ?>

        <div class="clear"></div>

        <footer id="footer" class="container_12" role="contentinfo">
            <p><a href="http://github.com/padraic/ZFPlanet">ZFPlanet</a> &copy; 2009 Pádraic Brady</p>
            <p>Powered by <a href="http://framework.zend.com">Zend Framework</a></p>
        </footer>

</body>
</html>
