<header class="article-header">
    <h2 class="entry-title">
        <a href="<?= $this->escape($this->entry->uri) ?>" rel="bookmark"><?= $this->escape($this->entry->title) ?></a>
    </h2>
    <small>Posted <time pubdate="pubdate" class="published updated"><?= $this->escape($this->entry->publishedDate) ?></time>
        (about <?= $this->timeSince($this->entry->publishedDate) ?> ago)
        by <address class="vcard author">
                <a href="<?= $this->escape($this->entry->Feed->Blog->uri) ?>" class="url fn">
                    <?= $this->escape($this->entry->author) ?>
                </a>
            </address>
        on <a href="<?= $this->escape($this->entry->Feed->Blog->uri) ?>"><?= $this->escape($this->entry->Feed->title) ?></a>
    </small>
</header>
<div class="entry-content article-body">
    <?= $this->shortenArticle($this->entry->content) ?>
</div>
<p><br/><a href="<?= $this->escape($this->entry->uri) ?>">Link to original article by
<?= $this->escape($this->entry->author) ?></a>
<? if($this->siteInfo('publisherId', 'sharethis')): ?>
    | <?= $this->shareThis($this->siteInfo('publisherId', 'sharethis'), $this->entry) ?>
<? endif; ?>
</p>
