#!/usr/bin/env php
<?php

if (!defined('APPLICATION_PATH')) {
    define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/../application'));
}

if (!defined('APPLICATION_ROOT')) {
    define('APPLICATION_ROOT', realpath(dirname(__FILE__) . '/..'));
}

set_include_path(
    APPLICATION_ROOT . '/library' . PATH_SEPARATOR
    . get_include_path()
);

require_once 'Zend/Loader/Autoloader.php';
$autoloader = Zend_Loader_Autoloader::getInstance();
$autoloader->setDefaultAutoloader(create_function('$class',
    "include str_replace('_', '/', \$class) . '.php';"
));


// check for app environment setting
$i = array_search('-e', $_SERVER['argv']);
if (!$i) {
    $i = array_search('--environment', $_SERVER['argv']);
}
if ($i) {
    define('APPLICATION_ENV', $_SERVER['argv'][$i+1]);
}

if (!defined('APPLICATION_ENV')) {
    if (getenv('APPLICATION_ENV')) {
        $env = getenv('APPLICATION_ENV');
    } else {
        $env = 'production';
    }
    define('APPLICATION_ENV', $env);
}

$application = new Zend_Application(
    APPLICATION_ENV,
    array(
        'config' => array(
            APPLICATION_PATH . '/configs/application.ini',
            APPLICATION_PATH . '/configs/cli.ini'
        )
    )
);

$application->bootstrap()->run();
